plugins {
    id 'java'
    id 'org.jetbrains.intellij.platform' version '2.13.1'
}

group 'cn.gudqs7.idea.plugins'
version '1.2.3'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        local(file("/home/gao/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate"))
        bundledPlugins("com.intellij.java")
    }
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.0'
    implementation 'org.yaml:snakeyaml:2.2'
    implementation 'org.apache.commons:commons-lang3:3.17.0'
    implementation 'commons-lang:commons-lang:2.6'
    implementation 'commons-collections:commons-collections:3.2.2'
    implementation 'commons-codec:commons-codec:1.17.1'
    implementation 'org.freemarker:freemarker:2.3.34'
    implementation 'com.youbenzi:MDTool:1.2.4'
    compileOnly 'org.projectlombok:lombok:1.18.40'
    annotationProcessor 'org.projectlombok:lombok:1.18.40'
}

intellijPlatform {
    pluginConfiguration {
        description = provider { file(descriptionFile).text }
        changeNotes = provider { file(changesFile).text }
        ideaVersion {
            untilBuild = ""
        }
    }
}

publishPlugin {
    channels = ['']
    token = System.getenv("JET_PUB_TOKEN")
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}
